prometheus/prombench

Makefile
manifests/kops/prometheus-ig.yaml
manifests/kops/regular-ig.yaml

@fabxc @brancz 
After this, it will spin up 1.5.2 clusters.
Also trimmed down the instance size for master since it's not going to be that busy.

Update to K8S 1.5.2 and trim down master size

---

apps/load-generator/Dockerfile
apps/load-generator/main.py
apps/load-generator/requirements.txt
spec.example.yaml

1. Add query group name
2. Try catch requests.exceptions.ConnectionError when querying prometheus intances
3. Enables specification of range queries with start, end and step parameters next to normal queries

Add query group name, catch connection errors and enable range queries

---

apps/fake-webserver/main.go
apps/fake-webserver/server.go

Those collections are relatively expensive (the former reads the
memstats, which requires a stop-the-world, the latter has to read and
parse a number of files in /proc). In high-frequency-scrape scenarios,
this might have a significant impact on performance.
@fabxc as discussed.

fake-webserver: Do not collect go_* and process_* metrics

---

provider/gke/gke.go

k8s objects can't have dots(.) se we added a custom function to allow normalising the variable values.

add template function to allow normalising variable values.

---

Dockerfile
Makefile
components/prombench/manifests/benchmark/2_loadgen.yaml
components/prombench/manifests/benchmark/3_prometheus-test.yaml
components/prombench/manifests/benchmark/4_node-exporter.yaml
components/prow/manifests/prow_internals_2.yaml

Benchmark comments are now
- /benchmark (If no release version is given, master is considered by default)
- /benchmark master
- /benchmark 2.3.0
- /benchmark stop
Prow does'nt seem to require GCS_BUCKET now

Modify files for different benchmark comments

---

components/prow/manifests/prow_internals_2.yaml

I don't see how is this useful and it just filling up the reports screen so removing for now and for checking real prow components status can revisit again.

remove echo test job

---

README.md
components/prow/manifests/prow_internals_2.yaml

this way we don't need to pass the env variable arround
and less likely to brake.
for local dev env can still use /etc/hosts
to point it to another prow installation.

replace INGESS_IP with a domain name

---

components/prombench/manifests/benchmark/2_loadgen.yaml
components/prombench/nodepools.yaml
components/prow/cluster.yaml

It is time to start testing PR's so setting higher machine types
and higher load settings for the loadgenertor.

change the bench machine types and loader configs

---

components/prombench/manifests/results/prometheus-meta.yaml
provider/k8s/k8s.go

it requests and dedicates a hdd
attached to the prometheus-meta pod
for persisisting the data
also added the command to the prombenh tool
to support this deployment type.

added PersistentVolumeClaim for prometheus-meta

---

provider/gke/gke.go

This is to handle errors like
`2018/08/02 03:48:47 Cluster in 'FailedPrecondition' state 'rpc error: code = FailedPrecondition desc = Operation operation-1533161820212-e0451fc6 is currently creating a node pool for cluster prombench. Please wait and try again once it is done.'`

Handle case of ongoing nodepool operation during creation

---

provider/k8s/k8s.go

yaml error parsing shows the line number of the culprit.
We split the object by "---" and  parse each object separately
so the yaml error line will be relative to the current object.
With this change we also display a small part of the text
so we know where in the main file is the error.

show the yaml config text when it can't be parsed.

---

Makefile
components/prombench/manifests/benchmark/2_fake-webserver.yaml
components/prombench/manifests/benchmark/2_loadgen.yaml
components/prombench/manifests/benchmark/3_prometheus-test.yaml
components/prow/manifests/prow_internals_2.yaml

fixes https://github.com/prometheus/prombench/issues/97
I also changes some docker tags to be all 2.0.0 so we match with the current prombench version.
This way we can always match the current prombench version with the image tag to be used.
All images have been uploaded to the prombench repo.

moved all dockerfile references to the prombench repo

---

components/prombench/manifests/benchmark/3_prometheus-test.yaml
components/prombench/manifests/results/prometheus-meta.yaml

~~this PR includes 2 changes, but since both are in the same file and  want to avoid merge conflicts I can't think of a better way to do this.~~
- fixes https://github.com/prometheus/prombench/issues/82 - just moved the order of the deployments and added a ready probe - this way we first start the pr builder and when Prometheus is started the probe will mark the deployment as ready and only than it will continue to deploy the release version.This reduced the graph time shift by only 2 secs 
~~- fixes https://github.com/prometheus/prombench/issues/90 - use named ports for Prometheus and just expose it as port 80. This way we even if we decide to change the port that Prometheus listens to wouldn't affect any other config.~~
UPDATE: the second change was done in …

Add ready probe for the builder.

---

README.md
components/prombench/apps/load-generator/main.py
components/prow/manifests/prow_internals_2.yaml
provider/k8s/k8s.go

remove extra ")" in the README
incorrect global variable assignment in the scaler/quirier
always pull latest image for plank
when failing to parse a yaml file while applying a resource,
display a small paragraph for easyer debugging.

some small bugs

---

components/prombench/manifests/benchmark/2_loadgen.yaml
components/prombench/manifests/benchmark/3_prometheus-test.yaml

untill we solve the problem with the scaling(didn't match node selector
error) will use 80 replicas for the fake server.
updated the prom builder probe. Looking at the logs this should work
well.
remove the custom settings for the pr buklder block retention
fixes: https://github.com/prometheus/prombench/issues/95
~~remove the settings to always pull the image for the release deployment
as these don't change so no need to download every time.~~

change deployment settings

---

Makefile

with this change I can use a custom AUTH_FILE location and use the
makefile locally.
When AUTH_FILE is not set it will use the default value.
Also broken the targets a bit to be able to remove/create nodes and
deployemts separately.
all changes are to make it easyer to use locally

refacotoring of the makefile to make it easyer to use locally

---

components/prombench/manifests/benchmark/2_loadgen.yaml
components/prombench/manifests/benchmark/3_prometheus-test.yaml
components/prombench/nodepools.yaml

this is the current setup that works best so far.
nodecount is increased to 7 as a single k8s node is limited to 100 pods to need 7 when we want to test the system with 700 pods

overall bench settings update.

---

components/prombench/manifests/benchmark/2_loadgen.yaml
components/prombench/manifests/benchmark/3_prometheus-test.yaml
components/prombench/nodepools.yaml

closes: #132
last SD bug was trigered with a small number of pods and a large number
of jobs.
this also allows us to use a single node for the fake-webserver.
This config is tested to utulize the fake-webserver node at 80% at 20
pods and the Prometheus nodes at around 60% avarage(we need some room
for the compaction processes).
Updated the scrape_interval: to 5s as this is closer to a real
production environment.

config-update to use many jobs with small number of pods

---

components/prombench/manifests/results/grafana_dashboard_prow_bench.yaml

Stacking graphs makes it even harder to compare versions.
Signed-off-by: Julius Volz <julius.volz@gmail.com>

Make all graphs un-stacked

---

cmd/prombench/prombench.go

Setting Lshortfile flag allows final file name and line number to be displayed when using the go's standard log. A sample output:
```
2018/09/18 17:00:25 main.go:9: Testing
```
Addresses: https://github.com/prometheus/prombench/issues/35

Setting Lshortfile flag to logger

---

components/prombench/manifests/results/grafana_dashboard_prow_bench.yaml

Separate timing , WAL fsync/latency graphs
Divide latency by _count to get average per query / request

Update grafana graphs
