prometheus/prombench

- Makefile
- wait-for-cluster.sh
This is an old PR that was targeted to the tmpl branch - not master branch. First tmpl was merged into master and then this PR was merged into tmpl. Thereby this code never made it into master.
@fabxc Could you merge these changes if they are still relevant for the project.
> Wait for all nodes and k8s cluster before deploying k8s manifests

- Makefile
- manifests/k8s/kube-state-metrics.yaml
- manifests/k8s/node-exporter.yaml
- manifests/k8s/prometheus-meta.yaml
- manifests/k8s/prometheus-test.yaml
- manifests/kops/prometheus-ig.yaml
- spec.example.yaml
Various changes that I had to do for testing the CPU performance regressions in 2.1.
@fabxc @Gouthamve @krasi-georgiev
> *: Various updates and stability changes

- Dockerfile
- components/prombench/pr-image-builder/Dockerfile
> remove deprecated maintainer label

- Dockerfile
> Update Dockerfile for new file structure

- README.md
- components/prombench/manifests/results/grafana_deployment.yaml
> Grafana admin password

- components/prow/manifests/prow_internals_2.yaml
> Hook deployment bug

- components/prombench/manifests/results/authenticate_rbac.yaml
This file was being ignored by my `.git/info/exclude` :stuck_out_tongue_winking_eye:
> add prometheus/grafana rbac-rules

- components/prow/manifests/prow_internals_2.yaml
> Remove sipian repo name from plugin config

- components/prombench/apps/load-generator/main.py
- components/prombench/manifests/benchmark/2_loadgen.yaml
- components/prow/manifests/prow_internals_2.yaml
> Replace env var with args

- provider/gke/gke.go
> Fix missing brace in deployments parse

- README.md
Fixes #62 and few other small changes.
> small nits and removed the reference to GCS_BUCKET

- temp/prometheus-builder/Dockerfile
- temp/prometheus-builder/Makefile
- temp/prometheus-builder/Makefile.common
- temp/prometheus-builder/README.md
- temp/prometheus-builder/build.sh
> Dockerfile and bash script to build and run prometheus from PR

- components/prow/manifests/prow_internals_2.yaml
> Add hook service-account and appropriate RBAC role

- provider/gke/gke.go
the current master doesn't build
> missing coma

- README.md
> rearange the readme and improve the wording.

- components/prombench/apps/load-generator/main.py
- components/prombench/manifests/benchmark/2_loadgen.yaml
- components/prombench/manifests/benchmark/3_prometheus-test.yaml
- components/prombench/manifests/benchmark/4_node-exporter.yaml
- components/prombench/manifests/results/grafana_deployment.yaml
- components/prombench/manifests/results/prometheus-meta.yaml
- components/prow/manifests/nginx-controller.yaml
- components/prow/manifests/prow_internals_2.yaml
> change all references to use port names instead of number

- components/prombench/manifests/benchmark/2_fake-webserver.yaml
- components/prombench/manifests/benchmark/2_loadgen.yaml
> Fix fake-webserver docker image url

- provider/gke/gke.go
> Fix return value of nodePoolCreated

- components/prombench/apps/load-generator/main.py
- components/prombench/manifests/benchmark/2_fake-webserver.yaml
- components/prombench/manifests/benchmark/2_loadgen.yaml
- components/prombench/manifests/benchmark/3_prometheus-test.yaml
> change scaling policy and number of fake-webserver pods in loadgen

- components/prombench/apps/load-generator/main.py
> scaller log missing parentheses

- provider/k8s/k8s.go
> more intelligent check for deployment readiness check

- components/prow/cluster.yaml
it errors for 1.10.4-gke.2 as it is not available anymore for the region
we are using.
> gke have updated the k8s version for the region we are using

- README.md
During the release of 2.4.0-rc, goutham said he could'nt find instructions on how to start benchmarking.
> Add instructions on how to use prombench in readme

- cmd/fake-webserver/main.go
Also, fix the `go vet` errors.
> Update use of prometheus.NewProcessCollector

- temp/prometheus-builder/README.md
> Fix link to deployment config in prometheus-builder readme

- README.md
> Document how to run manually without prow.
